config/routes.rb
Rails.application.routes.draw do
  resources :partidas
  devise_for :users 
  root "mainpage#index"
  delete "/mains" => "mains#delete_main", :as => 'delete_main'
  get "/mains" => "mains#index", as: 'mains' 
  post "/mains" => "mains#add_main", as: 'add_main'
  get "/usuarios" => "users#list_users", as: 'listar_usuarios'
  get "/usuarios/:id" => "users#profile", as: 'profile'
  post "/usuario/add" => "users#add_admin", as: 'add_admin'
  post "/usuario/remove" => "users#remove_admin", as: 'remove_admin'
  post "/punicao" => "users#aplica_punicao", as: 'pune_jogador'
  get "/historico" => "historico#list_by_user", as: 'historico_user'
  get "/historico/game/:id" => "historico#list_by_game", as: 'historico_game'
  get "/games" => "jogos#index", as: 'listar_jogos'
  get "/games/personagens/:jogo" => "jogos#personagens", as: 'lista_personagens'
  post "games/personagens/adicionar" => "jogos#adiciona_personagem", as: 'adiciona_personagem'
  post "games/personagens/reover" => "jogos#remove_personagem", as: 'remove_personagem'
  post "/games" => "jogos#new_game"
  post "/game/remove" => "jogos#remove_jogo", as: 'remove_jogo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/partida.rb
class PartidaValidator < ActiveModel::Validator
    def validate (record)
        unless (record.winP1 == 3 or record.winP2 == 3) and record.winP1 + record.winP2 <= 5
            record.errors[:resultados] << ": Por favor, insira um resultado válido."
        end
    end
end

class Partida < ApplicationRecord
    belongs_to :player1, class_name: "User"
    belongs_to :player2, class_name: "User"
    validates :player1, :player2, :winP1, :winP2, :game, presence: true
    validates_with PartidaValidator
    after_save :update_elos
    def update_elos
        elo1 = self.player1.elo(self.game)
        elo2 = self.player2.elo(self.game)
        total_games = self.winP1+self.winP2
        score1 = self.winP1/total_games.to_f
        score2 = self.winP2/total_games.to_f
        e1 = 1.0/(1+10**((elo2-elo1)/400.0))
        e2 = 1.0/(1+10**((elo1-elo2)/400.0))
        new_elo1 = elo1 + 32*(score1-e1)
        new_elo2 = elo2 + 32*(score2-e2)
        player1.update_elo(self.game, new_elo1.to_i)
        player2.update_elo(self.game, new_elo2.to_i)
    end
end

app/controllers/partidas_controller.rb
class PartidasController < ApplicationController
    before_action :set_partida, only: [:show, :edit, :update, :destroy]

    # GET /partidas
    # GET /partidas.json
    def index
        @partidas = Partida.all
    end

    # GET /partidas/1
    # GET /partidas/1.json
    def show
    end

    # GET /partidas/new
    def new
        @partida = Partida.new
    end

    # GET /partidas/1/edit
    def edit
        if !current_user.admin?
            redirect_to partidas_path
        end
    end

    # POST /partidas
    # POST /partidas.json
    def create
        p1 = current_user
        p2 = User.where("username = ?", partida_params[:player2])[0]
        winp1 = partida_params[:winP1]
        winp2 = partida_params[:winP2]
        game = partida_params[:game]
        @partida = Partida.new(player1: p1, player2: p2, winP1: winp1, winP2: winp2, game: game)
        respond_to do |format|
            if @partida.save
                format.html { redirect_to @partida, notice: 'Partida was successfully created.' }
                format.json { render :show, status: :created, location: @partida }
            else
                format.html { render :new }
                format.json { render json: @partida.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /partidas/1
    # PATCH/PUT /partidas/1.json
    def update
        if !current_user.admin?
            redirect_to partidas_path
            return
        else
            respond_to do |format|
                p1 = current_user
                p2 = User.where("username = ?", partida_params[:player2])[0]
                winp1 = partida_params[:winP1]
                winp2 = partida_params[:winP2]
                game = partida_params[:game]
                if @partida.update(player1: p1, player2: p2, winP1: winp1, winP2: winp2, game: game)

                    format.html { redirect_to @partida, notice: 'Partida was successfully updated.' }
                    format.json { render :show, status: :ok, location: @partida }
                else
                    format.html { render :edit }
                    format.json { render json: @partida.errors, status: :unprocessable_entity }
                end
            end
        end
    end

    # DELETE /partidas/1
    # DELETE /partidas/1.json
    def destroy
        if !current_user.admin?
            redirect_to partidas_path
        else
            @partida.destroy
            respond_to do |format|
                format.html { redirect_to partidas_url, notice: 'Partida removida com sucesso.' }
                format.json { head :no_content }
            end
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_partida
        @partida = Partida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partida_params
        params.require(:partida).permit(:winP1, :winP2, :player2, :game)
    end
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/views/partidas/_form.html.erb
<%= form_with(model: partida, local: true) do |form| %>
  <% if partida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(partida.errors.count, "erro") %> proibem esta partida de ser salva:</h2>

      <ul>
      <% partida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Jogo %>
    <%
      a = []
      Jogo.all.each do |u|
        a.push([u.nome, u.id])
      end
    %>

    <%= select :partida, :game, options_for_select(a) %>
  </div>

  <div class="field">
    <%= form.label :Player_1 %>
    <input id="partida_player1" value=<%=current_user%> readonly="readonly"/>
  </div>

  <div class="field">
    <%= form.label :Player_2 %>
    <%
      a = []
      User.all.each do |u|
        a.push([u.username,u]) if u != current_user
      end
    %>
    <%= select :partida, :player2, options_for_select(a) %>
    <!--
    <%= form.text_field :player2, id: :partida_player2 %>
    -->
    </div>

  <div class="field">
    <%= form.label :vitórias_de_P1 %>
    <%= form.number_field :winP1, id: :partida_winP1, value: 0 %>
  </div>

  <div class="field">
    <%= form.label :vitórias_de_P2 %>
    <%= form.number_field :winP2, id: :partida_winP2, value: 0 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/partidas/edit.html.erb
<h1>Editando Partida</h1>

<%= render 'form', partida: @partida %>

<%= link_to 'Mostrar', @partida %> |
<%= link_to 'Voltar', partidas_path %>

app/views/partidas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Partidas</h1>

<table>
  <thead>
    <tr>
      <th>Player1</th>
      <th>Player2</th>
      <th>VitóriasP1</th>
      <th>VitóriasP2</th>
      <th>Jogo</th>
    </tr>
  </thead>

  <tbody>
    <% @partidas.each do |partida| %>
      <tr>
        <% p1 = User.find(partida.player1_id) %>
        <td><%= p1.username %></td>
        <% p2 = User.find(partida.player2_id) %>
        <td><%= p2.username %></td>
        <td><%= partida.winP1 %></td>
        <td><%= partida.winP2 %></td>
        <td><%= Jogo.find(partida.game).nome %> </td>
        <td><%= link_to 'Mostrar', partida %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Editar', edit_partida_path(partida) %></td>
          <td><%= link_to 'Destruir', partida, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Partida', new_partida_path %>

app/views/partidas/new.html.erb
<h1>Nova Partida</h1>

<%= render 'form', partida: @partida %>

<%= link_to 'Voltar', partidas_path %>

app/views/partidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jogo:</strong>
  <%= Jogo.find(@partida.game) %>
</p>

<p>
  <strong>Player1:</strong>
  <% p1 = User.find(@partida.player1_id) %>
  <%= p1.username %>
</p>

<p>
<strong>Player2:</strong>
  <% p2 = User.find(@partida.player2_id) %>
  <%= p2.username %>
</p>

<p>
  <strong>VitóriasP1:</strong>
  <%= @partida.winP1 %>
</p>

<p>
  <strong>VitóriasP2:</strong>
  <%= @partida.winP2 %>
</p>

<%= link_to 'Editar', edit_partida_path(@partida) %> |
<%= link_to 'Voltar', partidas_path %>