config/routes.rb
Rails.application.routes.draw do
  resources :partidas
  devise_for :users 
  root "mainpage#index"
  delete "/mains" => "mains#delete_main", :as => 'delete_main'
  get "/mains" => "mains#index", as: 'mains' 
  post "/mains" => "mains#add_main", as: 'add_main'
  get "/usuarios" => "users#list_users", as: 'listar_usuarios'
  get "/usuarios/:id" => "users#profile", as: 'profile'
  post "/usuario/add" => "users#add_admin", as: 'add_admin'
  post "/usuario/remove" => "users#remove_admin", as: 'remove_admin'
  post "/punicao" => "users#aplica_punicao", as: 'pune_jogador'
  get "/historico" => "historico#list_by_user", as: 'historico_user'
  get "/historico/game/:id" => "historico#list_by_game", as: 'historico_game'
  get "/games" => "jogos#index", as: 'listar_jogos'
  get "/games/personagens/:jogo" => "jogos#personagens", as: 'lista_personagens'
  post "games/personagens/adicionar" => "jogos#adiciona_personagem", as: 'adiciona_personagem'
  post "games/personagens/reover" => "jogos#remove_personagem", as: 'remove_personagem'
  post "/games" => "jogos#new_game"
  post "/game/remove" => "jogos#remove_jogo", as: 'remove_jogo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
    validates_uniqueness_of :username
    after_create :start_elo
    has_and_belongs_to_many :personagem
    def initialize(*param)
        super(*param)
        self.admin = false
    end
    
    def start_elo
        Jogo.all.each {|j|
            if Elo.where ("jogo_id = #{j.id} and user_id = #{self.id}").empty?
                elo = Elo.new({user: self, jogo: j, elo: 1200})
                elo.save
            end
        }
    end
    
    def elo (jogo)
        query = Elo.where ("jogo_id = #{jogo} and user_id = #{self.id}")
        elo = query[0].elo
        return elo
    end
    
    def to_s
        return self.username
    end
    
    def partidas
        return Partida.where("player1_id = ? OR player2_id = ?", self.id, self.id)
    end
    
    def update_elo(jogo, new_elo)
        query = Elo.where ("jogo_id = #{jogo} and user_id = #{self.id}")
        elo = query[0]
        elo.update_column(:elo, new_elo)
    end
    
    def mains
        return self.personagem
    end
    
    def add_main (personagem)
        if self.personagem.where("personagem_id=#{personagem.id}").empty?
            self.personagem << personagem
        end
    end
    
    def delete_main (personagem)
        self.personagem.delete (personagem)
    end

    def add_admin
        self.admin = true
        self.save
    end

    def remove_admin
        self.admin = false
        self.save
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @jogos = Jogo.all
    end
    def list_users
        @usuarios = User.all
        @jogos = Jogo.all
    end
    def add_admin
    	id = params[:userId]
    	usuario = User.find(id)
    	usuario.add_admin()
        redirect_to listar_usuarios_path
    end
    def remove_admin
    	id = params[:userId]
    	usuario = User.find(id)
    	usuario.remove_admin()
    	redirect_to listar_usuarios_path
    end

    def aplica_punicao
        usuario = User.find(params[:userId])
        jogo = Jogo.find(params[:jogo])
        elo = usuario.elo(jogo.id) - (params[:pontos][:quantidade]).to_i
        puts(params[:pontos][:quantidade])
        usuario.update_elo(jogo.id, elo)
        redirect_to listar_usuarios_path
    end
    def profile
        @user = User.find params[:id]
        @jogos = Jogo.all
        @mains = @user.mains
    end
end

app/views/users/list_users.html.erb
<br>
<br>
<table>
	<thead>
		<tr>
			<th>Usuários</th>
			<th>Admin</th>
		</tr>
	</thead>
	<tbody>
		<% @usuarios.each do |usuario| %>
			<tr>
				<td>					
					<%= link_to usuario.username, profile_path(usuario.id) %>
				</td>
				<td>
					<%= usuario.admin %>
				</td>
				<% if current_user.admin? %>
					<td>
						<a  onclick="showModal('<%=usuario.username%>')" >Aplicar Punição</a>
					</td>
					<td>
						<% if current_user.username != usuario.username%>
							<% if !usuario.admin? %>
								<%= link_to 'Tornar Admin', add_admin_path(:userId => usuario.id), method: :post%>
							<% else %>
								<%= link_to 'Remover Admin', remove_admin_path(:userId => usuario.id), method: :post%>
							<% end %>
						<% end%>
					</td>
				<% end %>
				<div id='<%=usuario.username%>_modal' class="modal">
				 	<!-- Modal content -->
				  	<div class="modal-content">
				    	<span class="close" onclick="closeModal('<%=usuario.username%>')">&times;</span>
				    	<%= form_tag(pune_jogador_path(:userId=>usuario.id), method: :post) do %>
							<%= label_tag(:q, "Jogo") %>
							<%= select_tag(:jogo, options_from_collection_for_select(@jogos, :id, :nome)) %>
							<%= label_tag(:q, "Pontos a serem descontados") %>
							<%= number_field(:pontos, :quantidade, min: 1) %>
							<br>
							<%= submit_tag("Aplicar") %>
						<% end %>
				  	</div>
				</div>
			</tr>
		<% end %>
	</tbody>
</table>

<br>
<br>

<script>
// Get the modal
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 

function showModal(user) {
	var nome = user + "_modal"
	var modal = document.getElementById(nome);
	modal.style.display = "block";
}

function closeModal(user) {
	var nome = user + "_modal"
	var modal = document.getElementById(nome);
	modal.style.display = "none";
}

</script>

app/views/users/profile.html.erb
<h1><%= @user %></h1>
<br>

<table>
    <thead>
        <tr>
            <th>Jogo</th>
            <th>ELO</th>
        </tr>
    </thead>

    <tbody>
        <% for j in Jogo.all %>
        <tr>
            <td><%=j %></td>
            <td><%= @user.elo(j.id) %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<h2>Mains</h2>
<% for jogo in @jogos %>
        <% mains = @mains.where("jogo_id = ?", jogo.id) %>
        <% if mains.size > 0%>
            <table>
                <thead>
                    <th><%= jogo.nome%></th>    
                </thead>
                <tbody>
                    <% for personagem in mains %>
                        <tr>
                            <td><%= personagem.nome %></td>
                        </tr>
                    <%end%>
                </tbody>
            </table>
        <%end%>
    <br>
<% end %>