config/routes.rb
Rails.application.routes.draw do
  resources :partidas
  devise_for :users 
  root "mainpage#index"
  delete "/mains" => "mains#delete_main", :as => 'delete_main'
  get "/mains" => "mains#index", as: 'mains' 
  post "/mains" => "mains#add_main", as: 'add_main'
  get "/usuarios" => "users#list_users", as: 'listar_usuarios'
  get "/usuarios/:id" => "users#profile", as: 'profile'
  post "/usuario/add" => "users#add_admin", as: 'add_admin'
  post "/usuario/remove" => "users#remove_admin", as: 'remove_admin'
  post "/punicao" => "users#aplica_punicao", as: 'pune_jogador'
  get "/historico" => "historico#list_by_user", as: 'historico_user'
  get "/historico/game/:id" => "historico#list_by_game", as: 'historico_game'
  get "/games" => "jogos#index", as: 'listar_jogos'
  get "/games/personagens/:jogo" => "jogos#personagens", as: 'lista_personagens'
  post "games/personagens/adicionar" => "jogos#adiciona_personagem", as: 'adiciona_personagem'
  post "games/personagens/reover" => "jogos#remove_personagem", as: 'remove_personagem'
  post "/games" => "jogos#new_game"
  post "/game/remove" => "jogos#remove_jogo", as: 'remove_jogo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jogo.rb
class Jogo < ApplicationRecord
  after_create :start_elo
  def start_elo
    User.all.each {|u|
        if Elo.where ("jogo_id = #{self.id} and user_id = #{u.id}").empty?
            elo = Elo.new({user: u, jogo: self, elo: 1200})
            elo.save
        end
    }
  end
  def to_s
      return self.nome
  end
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
    def index
        @jogos = Jogo.all
    end
    def new_game
        Jogo.create ({nome: params[:nome]}) unless params[:nome].blank?
        redirect_to listar_jogos_path
    end
    def remove_jogo
    	@jogo = Jogo.find(params[:jogo])
    	if !current_user.admin?
            redirect_to listar_jogos_path
        else
            @jogo.destroy
            respond_to do |format|
                format.html { redirect_to listar_jogos_path, notice: 'Jogo removido com sucesso.' }
                format.json { head :no_content }
            end
        end
    end
    def personagens
    	@jogo = Jogo.find(params[:jogo])
    	@personagens = Personagem.where('jogo_id = ?', params[:jogo])
    end
    def adiciona_personagem
    	Personagem.create ({nome: params[:nome], jogo: Jogo.find(params[:jogo])}) unless params[:nome].blank?
    	redirect_to lista_personagens_path(:jogo => params[:jogo])
    end
    def remove_personagem
    	@personagem = Personagem.find(params[:char])
    	@personagem.destroy
        respond_to do |format|
            format.html { redirect_to lista_personagens_path(:jogo => params[:jogo]), notice: 'Personagem removido com sucesso.' }
            format.json { head :no_content }
        end
    end
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/views/jogos/index.html.erb
<table>
	<thead>
		<tr>
			<th>
				Jogos
			</th>
		</tr>
	</thead>
	<tbody>
	    <% @jogos.each do |jogo| %>
		    <tr>
		        <td><%=jogo.nome %></td>
		        <td><%= link_to "Personagens", lista_personagens_path(:jogo => jogo.id) %></td>
		        <td><%= link_to "Histórico", historico_game_path(jogo.id) %></td>
                <% if current_user.admin? %> <td><%= link_to "Remover Jogo", remove_jogo_path(:jogo => jogo.id), method: :post %></td> <% end %>
		    </tr>
	    <% end %>
	</tbody>
</table>

<% if current_user.admin? %>
<%= form_for :add_jogo do |f| %>
<input name = "nome"></input>
<%= submit_tag "Add game" %>
<% end %>
<% end %>

app/views/jogos/personagens.html.erb
<table>
    <thead>
        <tr>
            <th>Personagens</th>
        </tr>
    </thead>
    <tbody>
        <% for char in @personagens %>
        <tr>
            <td> <%= char.nome %> </td>
            <% if current_user.admin? %>
                <td><%= link_to "Remover Personagem", remove_personagem_path(:char => char.id, :jogo=>@jogo), method: :post %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

<% if current_user.admin? %>
    <%= form_tag(adiciona_personagem_path(:jogo=>@jogo), method: :post) do %>
        <%= text_field_tag(:nome) %>
        <%= submit_tag("Adiconar Personagem") %>
    <% end %>
<% end %>