config/routes.rb
Rails.application.routes.draw do
  resources :partidas
  devise_for :users 
  root "mainpage#index"
  delete "/mains" => "mains#delete_main", :as => 'delete_main'
  get "/mains" => "mains#index", as: 'mains' 
  post "/mains" => "mains#add_main", as: 'add_main'
  get "/usuarios" => "users#list_users", as: 'listar_usuarios'
  get "/usuarios/:id" => "users#profile", as: 'profile'
  post "/usuario/add" => "users#add_admin", as: 'add_admin'
  post "/usuario/remove" => "users#remove_admin", as: 'remove_admin'
  post "/punicao" => "users#aplica_punicao", as: 'pune_jogador'
  get "/historico" => "historico#list_by_user", as: 'historico_user'
  get "/historico/game/:id" => "historico#list_by_game", as: 'historico_game'
  get "/games" => "jogos#index", as: 'listar_jogos'
  get "/games/personagens/:jogo" => "jogos#personagens", as: 'lista_personagens'
  post "games/personagens/adicionar" => "jogos#adiciona_personagem", as: 'adiciona_personagem'
  post "games/personagens/reover" => "jogos#remove_personagem", as: 'remove_personagem'
  post "/games" => "jogos#new_game"
  post "/game/remove" => "jogos#remove_jogo", as: 'remove_jogo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Ladder</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body{font-family:Verdana, Arial, Helvetica, sans-serif;}>
        <a href="/"><%=image_tag ("/logo.png")%></a>
        <div id="divstyle">
            <ul>
                <li>
                    <%= link_to "Home", root_path %>
                </li>

                <li>
                    <%= link_to "Partidas", partidas_path %>
                </li>
                <li>
                    <%= link_to "Histórico", historico_user_path %>
                </li>
                <li>
                    <%= link_to "Jogos", listar_jogos_path %>
                </li>
                <li>
                    <%= link_to "Usuarios", listar_usuarios_path %>
                </li>

                <% if user_signed_in? %>
                    <li style="float:right">
                        <%= link_to "Sair",destroy_user_session_path, :method => :delete %>
                    </li>
                    <li style="float:right">
                        <%= link_to "Nova partida +",new_partida_path%>
                    </li>
                        <% else %>
                    <li style="float:right">
                        <div id="divstyle">
                            <%= link_to "Entrar",new_user_session_path %>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
        <p style = "color:#B30000; font-weight:bold;" class="notice"><%= notice %></p>
        <p style = "color:#B30000; font-weight:bold;" class="alert"><%= alert %></p>

        <div class="left-sidebar">
            <h3>Ranking</h3>
            <% @jogos = Jogo.all%>
            <select name="jogo" id="jogo" onchange="printRanks()" style="">
                <% @jogos.each do |u| %>
                <option value= <%=u.id%> > <%= u.nome%> </option>
                <% end %>

            </select>
            <p id="teste"></p>
        </div>
        <%= yield %>
    </body>
</html>
<script type="text/javascript">
    var aux = document.getElementById("jogo");
    printRanks();
    function printRanks() {
        var str="<table><tbody>";
        switch (aux.options[aux.selectedIndex].value) {
            <% for j in Jogo.all %>
                <% i = j.id %>
                case "<%= i %>":
                    str += "<% @users = User.all.sort_by {|x| -x.elo(i)} %>";
                    str += "<% @users.each do |u| %><tr><td> <%= u.username%></td><td> <%=u.elo(i)%> </td></tr><% end %>";
                    break;
            <% end %>
            str += "</tbody><table>";
        }
        console.log(str);
        document.getElementById("teste").innerHTML =  str;
    }
</script>